name: Build and Deploy
on: [push]
permissions:
  contents: write
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      # æ‹‰å–ä»£ç 
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      # # è®¾ç½®yarnç¼“å­˜ç›®å½•
      # - name: Get yarn cache directory path
      #   id: yarn-cache-dir-path
      #   run: echo "::set-output name=dir::$(yarn cache dir)"

      # # ä½¿ç”¨ç¼“å­˜
      # - name: Use cache
      #   uses: actions/cache@v1
      #   id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      #   with:
      #     path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
      #     key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-yarn-

      # # å®‰è£…ä¾èµ–
      # - name: Install
      #   run: |
      #     yarn

      # # æ‰“åŒ…
      # - name: Build ğŸ”§
      #   run: |
      #     yarn build

      - name: Install & Build
        run: |
          npm i
          npm run build

      # æ›´æ–°pagesçš„åˆ†æ”¯
      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/.vuepress/dist

      # åŒæ­¥åˆ°gitee
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          source-repo: git@github.com:noice-lee/my-articles.git
          destination-repo: git@gitee.com:noice__li/my-articles.git
